name = "DynamicComputationGraphs"
uuid = "591544fa-5de1-11e9-31f7-cbfeeb0dfc0e"
authors = ["Philipp Gabler <phipsgabler@users.noreply.github.com>"]
version = "0.2.0"

[deps]
IRTools = "7869d1d1-7146-5819-86e3-90919afe41df"

[compat]
julia = "1.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[targets]
test = ["Test", "Distributions", "Random"]
