name = "DynamicComputationGraphs"
uuid = "591544fa-5de1-11e9-31f7-cbfeeb0dfc0e"
authors = ["Philipp Gabler <phipsgabler@users.noreply.github.com>"]
version = "0.2.0"

[deps]
IRTools = "7869d1d1-7146-5819-86e3-90919afe41df"

[compat]
julia = "1.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
